version: "3.3"

services:
  dist:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - vdist:/dist
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - vdist:/var/www/html
    ports:
      - "4200:80"
    networks:
      - nginx
volumes:
  vdist:
networks:
  nginx: