version: "3.3"

services:
  dist:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "npm -v
      && npm run build
      && ls dist/app"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - dist
    volumes:
      - ./dist/app:/var/www/html
    ports:
      - "4200:80"
    networks:
      - nginx
volumes:
  distFront:
networks:
  nginx: