version: "3.3"

services:
  dist:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - distFront:/app/dist/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - distFront:/var/www/html
    ports:
      - "4200:80"
    networks:
      - nginx
volumes:
  distFront: {}
networks:
  nginx: